### ISSUE TITLE
The result on s3dis_Aera5

### ISSUE THREAD

**Issue by mooncakehub** [anhthuan1999/PointCT#3]
thank you for your excellent work! I run PointCT on a single 409GPU,the test result on S3DIS Aera5 as this，my parameter settings are the same as the default parameters in your code, is this result too different and what do you think is causing this? Thank you for your reply!
![1710407130462](https://github.com/anhthuan1999/PointCT/assets/138660085/fcf66a24-eda3-4e13-94d0-e6d2710fdb0a)

**Comment by anhthuan1999** [comment]
Hi. Thanks for your interesting in our work. Is it come from test.py? If yes, maybe the batch size and num of gpu during training has effect. We test on batch size 4 for 2 gpu. It means that each gpu use 2 batches. But I am not sure about my claim. Please correct me if I was wrong.

**Comment by anhthuan1999** [comment]
Thanks for your interesting in our work. Do you test it on model_best.pth?

**Comment by mooncakehub** [comment]
yes，this is my config/s3dis.yaml:
```
DATA:
  data_name: s3dis
  data_root: /home/cm/share/Fxy/PointCT-main/data/stanford_indoor3d #data path
  test_area: 5
  classes: 13
  fea_dim: 6
  voxel_size: 0.04
  voxel_max: 80000
  loop: 30

TRAIN:
  arch: weak
  use_xyz: True
  sync_bn: False
  ignore_label: 255
  train_gpu: [0]
  workers: 16  # data loader workers
  batch_size: 4  # batch size for training
  batch_size_val: 2  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0005 #0.0005
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.1 #0.1 #0.0001
  drop_rate: 0.5
  manual_seed: 7777
  print_freq: 1
  save_freq: 1
  save_path:  /home/cm/share/Fxy/PointCT-main/train_model # save model path
  weight:  # path to initial weight (default: none)
  resume: # resume from previous steps (suggest: model_last.pth)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
  labeled_point: 1%
  
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_list: #test list (applied only to s3dis with val5.txt)
  test_list_full: # applied only to s3dis: val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [5]
  test_workers: 4
  batch_size_test: 4
  model_path:  /home/cm/share/Fxy/PointCT-main/train_model/model/model_best.pth # model path for testing (suggest: model_best.pth)
  save_folder:  /home/cm/share/Fxy/PointCT-main/result # save result folder
  names_path: /home/cm/share/Fxy/PointCT-main/data/s3dis_names.txt # s3dis_names.txt
```
